version: '3.1'
services:
  ewm-service:
    build: ./ewm-service
    image: ewm_service_image
    container_name: ewm-service

    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-server:
    build: ./ewm-stats/service
    image: stats_service_image
    container_name: stats-server

    ports:
      - "9090:9090"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-postgress
    restart: always
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
